dist: xenial
language: go
go:
  - "1.11.x"

env:
  - GO111MODULE=on GOFLAGS=-mod=vendor

jobs:
  include:
    - stage: test
      script:
        - make tools
        - make test
      on:
        branch: "master"
